#!/bin/bash
function deleteJs {
  fullfile=$1
  filename=$(basename "$fullfile")
  filename="${filename%.*}"
  rm -v $filename".js"
}

# find all coffee files, strip .coffee, delete .js
find . -name "*.coffee" | while read file; do deleteJs "$file"; done

exit 0
