// Generated by CoffeeScript 1.6.3
(function() {
  var Map;

  Map = (function() {
    function Map(width, height) {
      this.width = width;
      this.height = height;
    }

    Map.prototype.middle = function() {
      return {
        x: this.width / 2.0,
        y: this.height / 2.0
      };
    };

    Map.prototype.inBounds = function(x, y) {
      console.log(x, y);
      return (0 <= x && x < this.width) && (0 <= y && y < this.height);
    };

    return Map;

  })();

  exports.Map = Map;

}).call(this);
